In [1]:
import pandas as pd
import numpy as np 
import sys
sys.path.append("../tax-calculator")
from taxcalc.records import Records
from taxcalc import Policy, Records, Calculator, Behavior, behavior, Growth
from taxcalc.utils import *
from numpy.testing import assert_array_almost_equal
import matplotlib
import matplotlib.pyplot as plt 
from matplotlib.transforms import BlendedGenericTransform
%matplotlib inline
import copy
import itertools

In [2]:
import taxcalc
taxcalc._version.get_versions()

{'full': '4fb4abaca1388537137912419496ea8366c513a1', 'version': '0.6.6'}

In [3]:
puf = pd.read_csv("../tax-calculator/true_puf.csv")
policy_base = Policy()
records_base = Records(puf)

policy_reform = Policy()
records_reform = Records(puf)
grow = Growth()

policy_reform2 = Policy()
records_reform2 = Records(puf)
grow2 = Growth()

policy_reform3 = Policy()
records_reform3 = Records(puf)

policy_reform4 = Policy()
records_reform4 = Records(puf)
grow4 = Growth()

calcbase = Calculator(policy = policy_base, records = records_base)
calcreform = Calculator(policy = policy_reform, records = records_reform, growth = grow)
calcreform2 = Calculator(policy = policy_reform2, records = records_reform2, growth = grow2)
calcreform3 = Calculator(policy = policy_reform3, records = records_reform3)
calcreform4 = Calculator(policy = policy_reform4, records = records_reform4, growth = grow4)

You loaded data for 2009.
Your data have been extrapolated to 2013.
You loaded data for 2009.
Your data have been extrapolated to 2013.
You loaded data for 2009.
Your data have been extrapolated to 2013.
You loaded data for 2009.
Your data have been extrapolated to 2013.
You loaded data for 2009.
Your data have been extrapolated to 2013.

In [4]:
    reform1 = {2016: {'_STD': [[6300,12600,6300,9300,12600, 6300, 1050]],
                    '_ID_BenefitSurtax_crt': [0.0],
                    '_II_rt1': [0.12],
                     '_II_rt2': [0.12],
                     '_II_rt3': [0.25],
                     '_II_rt4': [0.25],
                     '_II_rt5': [0.33],
                     '_II_rt6': [0.33],
                     '_II_rt7': [0.33],
                    '_AMT_trt1':[0],
                     '_AMT_trt2':[0]}
                    }
   
    reform2 = {2016: {'_STD': [[6300,12600,6300,9300,12600, 6300, 1050]],
                      '_II_rt1': [0.12],
                     '_II_rt2': [0.12],
                     '_II_rt3': [0.25],
                     '_II_rt4': [0.25],
                     '_II_rt5': [0.33],
                     '_II_rt6': [0.33],
                     '_II_rt7': [0.33],
                    '_AMT_trt1':[0],
                     '_AMT_trt2':[0]}
                    }
    reform3 = {2016: {'_ID_BenefitSurtax_crt': [0.0]
                    }
               }
   
    policy_reform.implement_reform(reform2)
    policy_reform2.implement_reform(reform3)
    policy_reform3.implement_reform(reform3)
    grow2.update_economic_growth({2016: {'_factor_adjustment': [0.5]}})
    grow.update_economic_growth({2016: {'_factor_adjustment': [0.5]}})
    grow4.update_economic_growth({2016: {'_factor_adjustment': [0.5]}})

In [5]:
    calcbase.advance_to_year(2016)
    calcreform.advance_to_year(2016)
    calcreform2.advance_to_year(2016)
    calcreform3.advance_to_year(2016)
    calcreform4.advance_to_year(2016)

In [6]:
calcbase.calc_all()
calcreform.calc_all()
calcreform2.calc_all()
calcreform3.calc_all()
calcreform4.calc_all()

In [8]:
multiyear_diagnostic_table(calcreform, 10)

,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
Returns (#m),170.1,172.4,174.1,175.6,177.1,178.4,179.8,181.0,182.3,183.6
AGI ($b),"15,741.8","24,559.6","38,189.8","59,160.7","91,638.7","141,950.0","219,916.5","340,659.2","527,675.2","817,378.3"
Itemizers (#m),46.8,48.0,48.9,49.5,50.1,50.5,51.0,51.5,52.0,52.4
Itemized Deduction ($b),"1,951.2","2,998.2","4,599.9","7,025.0","10,757.3","16,519.9","25,494.0","39,415.7","61,038.6","94,597.8"
Standard Deduction Filers (#m),110.3,112.3,115.8,119.5,121.4,122.6,123.6,124.4,125.3,126.1
Standard Deduction ($b),980.2,"1,017.7","1,077.6","1,138.0","1,185.5","1,227.7","1,269.9","1,310.4","1,352.8","1,396.6"
Personal Exemption ($b),"1,160.5","1,119.8","1,014.0",866.3,686.6,510.3,363.8,239.1,152.9,90.6
Taxable income ($b),"12,085.1","19,922.4","32,149.6","51,024.9","80,274.9","125,592.5","195,695.6","304,149.1","472,022.0","731,947.8"
Regular Tax ($b),"2,620.6","4,698.1","8,200.4","13,915.5","23,094.1","37,632.7","60,402.6","95,881.3","151,011.4","236,562.1"
AMT income ($b),"14,699.0","22,931.7","35,638.3","55,185.0","85,446.3","132,296.6","204,838.3","317,134.5","491,012.2","760,242.2"
AMT amount ($b),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AMT number (#m),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Tax before credits ($b),"2,486.4","4,490.9","7,881.9","13,431.6","22,356.5","36,507.7","58,680.4","93,235.3","146,936.1","230,271.6"
refundable credits ($b),91.4,75.5,74.1,91.3,124.5,180.1,270.7,409.2,627.8,967.7
nonrefundable credits ($b),90.7,113.6,144.5,192.5,273.8,409.0,621.2,954.3,"1,472.3","2,274.7"
Misc. Surtax ($b),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Ind inc tax ($b),"2,425.7","4,486.9","7,943.5","13,567.9","22,586.8","36,846.5","59,153.9","93,896.2","147,866.7","231,610.2"
Payroll tax ($b),"1,423.4","1,960.0","2,619.2","3,459.2","4,587.3","6,175.8","8,499.5","11,965.1","17,206.0","25,195.2"
Combined liability ($b),"3,849.1","6,446.9","10,562.7","17,027.1","27,174.1","43,022.3","67,653.4","105,861.4","165,072.8","256,805.4"

In [9]:
multiyear_diagnostic_table(calcreform2, 10)

,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
Returns (#m),170.1,172.4,174.1,175.6,177.1,178.4,179.8,181.0,182.3,183.6
AGI ($b),"15,741.8","24,559.6","38,189.8","59,160.7","91,638.7","141,950.0","219,916.5","340,659.2","527,675.2","817,378.3"
Itemizers (#m),46.6,47.8,48.7,49.3,49.9,50.4,50.9,51.5,51.9,52.4
Itemized Deduction ($b),"1,935.7","2,979.1","4,577.3","6,997.5","10,723.4","16,481.0","25,439.9","39,336.8","60,923.1","94,420.1"
Standard Deduction Filers (#m),110.6,112.5,116.0,119.6,121.5,122.7,123.7,124.5,125.3,126.2
Standard Deduction ($b),983.4,"1,020.4","1,079.6","1,139.8","1,186.7","1,228.5","1,270.4","1,310.8","1,353.2","1,396.9"
Personal Exemption ($b),"1,160.5","1,119.8","1,014.0",866.3,686.6,510.3,363.8,239.1,152.9,90.6
Taxable income ($b),"12,096.8","19,938.1","32,169.5","51,048.6","80,303.8","125,625.6","195,740.3","304,214.4","472,116.6","732,092.8"
Regular Tax ($b),"2,877.3","5,162.1","9,032.4","15,444.2","25,933.5","42,842.8","69,682.2","111,836.3","177,626.1","279,967.1"
AMT income ($b),"14,694.7","22,925.7","35,630.9","55,175.8","85,432.8","132,277.2","204,808.3","317,092.1","490,948.8","760,144.4"
AMT amount ($b),74.0,149.5,255.1,368.1,482.3,605.3,769.5,"1,012.9","1,410.4","2,037.4"
AMT number (#m),11.1,21.8,31.8,36.0,34.0,28.6,21.9,15.8,11.2,9.0
Tax before credits ($b),"2,766.9","5,022.6","8,836.1","15,114.9","25,335.4","41,778.0","67,871.0","108,864.3","172,882.5","272,491.3"
refundable credits ($b),92.2,76.1,74.3,91.4,124.5,180.1,270.7,409.2,627.8,967.7
nonrefundable credits ($b),90.5,114.1,145.9,194.6,276.7,413.0,626.7,962.7,"1,484.9","2,294.4"
Misc. Surtax ($b),351.2,640.9,"1,131.2","1,971.9","3,339.5","5,499.1","8,866.1","14,073.7","22,134.2","34,641.9"
Ind inc tax ($b),"3,056.9","5,658.6","10,027.3","17,220.9","28,902.2","47,611.8","77,205.1","123,590.6","195,934.7","308,452.1"
Payroll tax ($b),"1,423.4","1,960.0","2,619.2","3,459.2","4,587.3","6,175.8","8,499.5","11,965.1","17,206.0","25,195.2"
Combined liability ($b),"4,480.3","7,618.6","12,646.6","20,680.1","33,489.6","53,787.7","85,704.6","135,555.7","213,140.7","333,647.3"

In [10]:
multiyear_diagnostic_table(calcreform4, 10)

,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
Returns (#m),170.1,172.4,174.1,175.6,177.1,178.4,179.8,181.0,182.3,183.6
AGI ($b),"15,741.8","24,559.6","38,189.8","59,160.7","91,638.7","141,950.0","219,916.5","340,659.2","527,675.2","817,378.3"
Itemizers (#m),46.6,47.8,48.7,49.3,49.9,50.4,50.9,51.5,51.9,52.4
Itemized Deduction ($b),"1,935.7","2,979.1","4,577.3","6,997.5","10,723.4","16,481.0","25,439.9","39,336.8","60,923.1","94,420.1"
Standard Deduction Filers (#m),110.6,112.5,116.0,119.6,121.5,122.7,123.7,124.5,125.3,126.2
Standard Deduction ($b),983.4,"1,020.4","1,079.6","1,139.8","1,186.7","1,228.5","1,270.4","1,310.8","1,353.2","1,396.9"
Personal Exemption ($b),"1,160.5","1,119.8","1,014.0",866.3,686.6,510.3,363.8,239.1,152.9,90.6
Taxable income ($b),"12,096.8","19,938.1","32,169.5","51,048.6","80,303.8","125,625.6","195,740.3","304,214.4","472,116.6","732,092.8"
Regular Tax ($b),"2,877.3","5,162.1","9,032.4","15,444.2","25,933.5","42,842.8","69,682.2","111,836.3","177,626.1","279,967.1"
AMT income ($b),"14,694.7","22,925.7","35,630.9","55,175.8","85,432.8","132,277.2","204,808.3","317,092.1","490,948.8","760,144.4"
AMT amount ($b),74.0,149.5,255.1,368.1,482.3,605.3,769.5,"1,012.9","1,410.4","2,037.4"
AMT number (#m),11.1,21.8,31.8,36.0,34.0,28.6,21.9,15.8,11.2,9.0
Tax before credits ($b),"2,766.9","5,022.6","8,836.1","15,114.9","25,335.4","41,778.0","67,871.0","108,864.3","172,882.5","272,491.3"
refundable credits ($b),92.2,76.1,74.3,91.4,124.5,180.1,270.7,409.2,627.8,967.7
nonrefundable credits ($b),90.5,114.1,145.9,194.6,276.7,413.0,626.7,962.7,"1,484.9","2,294.4"
Misc. Surtax ($b),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Ind inc tax ($b),"2,705.6","5,017.6","8,896.2","15,249.0","25,562.8","42,112.8","68,339.0","109,516.8","173,800.5","273,810.2"
Payroll tax ($b),"1,423.4","1,960.0","2,619.2","3,459.2","4,587.3","6,175.8","8,499.5","11,965.1","17,206.0","25,195.2"
Combined liability ($b),"4,129.1","6,977.7","11,515.4","18,708.2","30,150.1","48,288.6","76,838.4","121,482.0","191,006.5","299,005.5"